spring:
  application:
    name: demo
  devtools:
    restart:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mariadb://localhost:3306/dev
    username: root
    password: qpalzm0915
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 60
      max-lifetime: 300000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        generate_statistics: false
        use_sql_comments: false
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
        type:
          descriptor:
            sql: false
    generate-ddl: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  thymeleaf:
    enabled: false
  redis:
    database: 0
    host: 192.168.10.54
    port: 6379
    password:
  config:
    activate:
      on-profile: master
  servlet:
    multipart:
      location: '/upload/temp'
      max-file-size: 8MB
      max-request-size: 60MB
      file-size-threshold: 60MB
  lifecycle:
    timeout-per-shutdown-phase: 10s
  sql:
    init:
      mode: always
springdoc:
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: rest-api-doc.html
    default-models-expand-depth: -1
jwt:
  secret: secretKey-test-authorization-jwt-manage-tokensecretKey-test-authorization-jwt-manage-tokensecretKey-test-authorization-jwt-manage-tokensecretKey-test-authorization-jwt-manage-tokensecretKey-test-authorization-jwt-manage-token
  accessTokenValidity: 3d
  refreshTokenValidity: 30d
server:
  port: 8500
  compression:
    enabled: true
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  error:
    # path: /error
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부

---

spring:
  application:
    name: demo
  devtools:
    restart:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mariadb://localhost:3306/dev
    username: root
    password: qpalzm0915
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 60
      max-lifetime: 300000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        generate_statistics: false
        use_sql_comments: false
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
        type:
          descriptor:
            sql: false
    generate-ddl: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  thymeleaf:
    enabled: false
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
  config:
    activate:
      on-profile: develop
  servlet:
    multipart:
      location: '/upload/temp'
      max-file-size: 8MB
      max-request-size: 60MB
      file-size-threshold: 60MB
  lifecycle:
    timeout-per-shutdown-phase: 10s
  sql:
    init:
      mode: always
springdoc:
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: rest-api-doc.html
    default-models-expand-depth: -1
jwt:
  secret: secretKey-test-authorization-jwt-manage-tokensecretKey-test-authorization-jwt-manage-tokensecretKey-test-authorization-jwt-manage-tokensecretKey-test-authorization-jwt-manage-tokensecretKey-test-authorization-jwt-manage-token
  accessTokenValidity: 1h
  refreshTokenValidity: 3d
server:
  port: 8500
  compression:
    enabled: true
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  error:
    # path: /error
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부